version: "3.8"
services:
  rag3:
    build:
      context: .
      dockerfile: rag/Dockerfile.rag
    hostname: rag3
    ports:
      - "8001:8000"
      - "8002:8000"
      - "8003:8000"
    command:
      - python3
      - "-u"
      - rag_pipeline.py
      - "3"
      - "8000"
      - "rag1:9000"
      - "rag2:9000"
      - bert-base-uncased
      - ../knowledge/
      - google/gemini-2.0-pro-exp-02-05:free
#      - rag_network

# why is this needed
#networks:
#  rag_network:
#    driver: bridge
